complete -c spotify-cli -n "not __fish_seen_subcommand_from auth player track search album artist playlist device help system" -a "auth player track search album artist playlist device help system"
complete -c spotify-cli -s v -l verbose -d "Verbose output"
complete -c spotify-cli -l json -d "Output JSON"
complete -c spotify-cli -l no-trunc -d "Disable table truncation"
complete -c spotify-cli -l width -d "Max table column width"

complete -c spotify-cli -n "__fish_seen_subcommand_from auth" -a "login status scopes logout"
complete -c spotify-cli -n "__fish_seen_subcommand_from auth" -l client-id -d "Spotify client id"

complete -c spotify-cli -n "__fish_seen_subcommand_from player" -a "play pause next prev status"
complete -c spotify-cli -n "__fish_seen_subcommand_from track" -a "like unlike info"
complete -c spotify-cli -n "__fish_seen_subcommand_from album" -a "info play"
complete -c spotify-cli -n "__fish_seen_subcommand_from album" -l fuzzy -d "Fuzzy match"
complete -c spotify-cli -n "__fish_seen_subcommand_from album" -l user -d "Use market from token"
complete -c spotify-cli -n "__fish_seen_subcommand_from album" -l pick -d "Pick a specific result"
complete -c spotify-cli -n "__fish_seen_subcommand_from album" -l last -d "Use cached search"
complete -c spotify-cli -n "__fish_seen_subcommand_from album" -l search -d "Search query"
complete -c spotify-cli -n "__fish_seen_subcommand_from artist" -a "info play"
complete -c spotify-cli -n "__fish_seen_subcommand_from artist" -l fuzzy -d "Fuzzy match"
complete -c spotify-cli -n "__fish_seen_subcommand_from artist" -l user -d "Use market from token"
complete -c spotify-cli -n "__fish_seen_subcommand_from artist" -l pick -d "Pick a specific result"
complete -c spotify-cli -n "__fish_seen_subcommand_from artist" -l last -d "Use cached search"
complete -c spotify-cli -n "__fish_seen_subcommand_from artist" -l search -d "Search query"

complete -c spotify-cli -n "__fish_seen_subcommand_from search" -l type -d "Search type"
complete -c spotify-cli -n "__fish_seen_subcommand_from search" -l fuzzy -d "Fuzzy match"
complete -c spotify-cli -n "__fish_seen_subcommand_from search" -l user -d "Use market from token"
complete -c spotify-cli -n "__fish_seen_subcommand_from search" -l limit -d "Limit results"
complete -c spotify-cli -n "__fish_seen_subcommand_from search" -l pick -d "Pick a specific result"
complete -c spotify-cli -n "__fish_seen_subcommand_from search" -l last -d "Use cached search"
complete -c spotify-cli -n "__fish_seen_subcommand_from search" -l play -d "Play first result"

complete -c spotify-cli -n "__fish_seen_subcommand_from playlist" -a "list info play add follow unfollow pin"
complete -c spotify-cli -n "__fish_seen_subcommand_from playlist; and __fish_seen_subcommand_from list" -l collaborative -d "Only collaborative playlists"
complete -c spotify-cli -n "__fish_seen_subcommand_from playlist; and __fish_seen_subcommand_from list" -l owned -d "Only owned playlists"
complete -c spotify-cli -n "__fish_seen_subcommand_from playlist; and __fish_seen_subcommand_from list" -l public -d "Only public playlists"
complete -c spotify-cli -n "__fish_seen_subcommand_from playlist; and __fish_seen_subcommand_from list" -l private -d "Only private playlists"
complete -c spotify-cli -n "__fish_seen_subcommand_from playlist; and __fish_seen_subcommand_from list" -l sort -d "Sort playlists"
complete -c spotify-cli -n "__fish_seen_subcommand_from playlist; and __fish_seen_subcommand_from list" -l sort -a "name owner public collaborative"
complete -c spotify-cli -n "__fish_seen_subcommand_from playlist; and __fish_seen_subcommand_from info play add follow unfollow" -l fuzzy -d "Fuzzy match"
complete -c spotify-cli -n "__fish_seen_subcommand_from playlist; and __fish_seen_subcommand_from info play add follow unfollow" -l user -d "Use market from token"
complete -c spotify-cli -n "__fish_seen_subcommand_from playlist; and __fish_seen_subcommand_from info play add follow unfollow" -l pick -d "Pick a specific result"
complete -c spotify-cli -n "__fish_seen_subcommand_from playlist; and __fish_seen_subcommand_from info play add follow unfollow" -l last -d "Use cached search"
complete -c spotify-cli -n "__fish_seen_subcommand_from playlist; and __fish_seen_subcommand_from info play add follow unfollow" -a "(spotify-cli complete playlist 2>/dev/null)"

complete -c spotify-cli -n "__fish_seen_subcommand_from device" -a "list set"
complete -c spotify-cli -n "__fish_seen_subcommand_from device; and __fish_seen_subcommand_from list" -l live -d "Query Spotify directly"
complete -c spotify-cli -n "__fish_seen_subcommand_from device; and __fish_seen_subcommand_from set" -a "(spotify-cli complete device 2>/dev/null)"

complete -c spotify-cli -n "__fish_seen_subcommand_from cache" -a "status country user"
complete -c spotify-cli -n "__fish_seen_subcommand_from playlist; and __fish_seen_subcommand_from pin" -a "add remove list play"
complete -c spotify-cli -n "__fish_seen_subcommand_from playlist; and __fish_seen_subcommand_from pin; and __fish_seen_subcommand_from remove play" -a "(spotify-cli complete pin 2>/dev/null)"
complete -c spotify-cli -n "__fish_seen_subcommand_from completions" -a "bash zsh fish"
complete -c spotify-cli -n "__fish_seen_subcommand_from system" -a "sync cache completions"
