//! Library (liked songs) command handlers

use crate::endpoints::library::{check_saved_tracks, get_saved_tracks, remove_tracks, save_tracks};
use crate::endpoints::player::get_playback_state;
use crate::io::output::{ErrorKind, Response};

use super::with_client;

// Generate standard resource commands using macros
resource_list!(library_list, get_saved_tracks::get_saved_tracks, "Saved tracks");
resource_remove!(library_remove, remove_tracks::remove_tracks, "track");
resource_check!(library_check, check_saved_tracks::check_saved_tracks);

// library_save has custom --now-playing logic, so it's not generated by macro
pub async fn library_save(ids: &[String], now_playing: bool) -> Response {
    // Validate input
    if ids.is_empty() && !now_playing {
        return Response::err(400, "Provide track IDs or use --now-playing", ErrorKind::Validation);
    }

    let explicit_ids = ids.to_vec();

    with_client(|client| async move {
        let mut all_ids = explicit_ids;

        // Add now playing track if requested
        if now_playing {
            match get_playback_state::get_playback_state(&client).await {
                Ok(Some(state)) => {
                    if let Some(id) = state
                        .get("item")
                        .and_then(|i| i.get("id"))
                        .and_then(|v| v.as_str())
                    {
                        all_ids.push(id.to_string());
                    } else {
                        return Response::err(404, "Nothing currently playing", ErrorKind::Player);
                    }
                }
                Ok(None) => return Response::err(404, "Nothing currently playing", ErrorKind::Player),
                Err(e) => return Response::from_http_error(&e, "Failed to get playback state"),
            }
        }

        let count = all_ids.len();
        match save_tracks::save_tracks(&client, &all_ids).await {
            Ok(_) => Response::success(200, format!("Saved {} track(s)", count)),
            Err(e) => Response::from_http_error(&e, "Failed to save tracks"),
        }
    }).await
}
